# auth-test.yaml
name: Auth test
run-name: Auth test by @${{ github.actor }}

on:
  workflow_dispatch: # Manually run

permissions:
  contents: read
  id-token: write

env:
  PROJECT_ID: ksst-genai-app
  PROJECT_NUMBER: 329656168601

jobs:
  auth_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Auth
        uses: google-github-actions/auth@v2
        with:
          project_id: ${{ env.PROJECT_ID }}
          workload_identity_provider: projects/${{ env.PROJECT_NUMBER }}/locations/global/workloadIdentityPools/github-actions/providers/github-actions
          service_account: genai-app-cicd@${{ env.PROJECT_ID }}.iam.gserviceaccount.com

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Use Cloud SDK
        run: gcloud config list

      - name: Use Cloud SDK
        run: gcloud artifacts docker images list asia-northeast1-docker.pkg.dev/ksst-genai-app/genai-app
