name: Deploy CloudRun
on:
  release:
    types: [published]
env:
  DOCKER_REGISTRY: asia-northeast1-docker.pkg.dev
  REPOSITORY: genai-app
  PROJECT_ID: ksst-genai-app
  PROJECT_NUMBER: 329656168601
  SERVICE_NAME: english-learning-feedback

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - id: "auth"
        name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          project_id: ${{ env.PROJECT_ID }}
          workload_identity_provider: projects/${{ env.PROJECT_NUMBER }}/locations/global/workloadIdentityPools/github-actions/providers/github-actions
          service_account: genai-app-cicd@${{ env.PROJECT_ID }}.iam.gserviceaccount.com

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          version: ">= 379.0.0"

      - name: Configure Artifact Registry
        run: gcloud auth configure-docker ${{ env.REGISTRY }}

      - name: Build, tag and push container
        id: build-image
        uses: docker/build-push-action@v6
        with:
          context: ./
          push: true
          tags: asia-northeast1-docker.pkg.dev/ksst-genai-app/genai-app/english-learning-feedback:${{ github.event.release.tag_name }}

      - name: Deploy
        run: gcloud run deploy ${{ env.SERVICE_NAME }} --image asia-northeast1-docker.pkg.dev/ksst-genai-app/genai-app/english-learning-feedback:${{ github.event.release.tag_name }} --platform managed --region asia-northeast1 --allow-unauthenticated --max-instances 1 --min-instances 0 --memory 512Mi
